### PR TITLE
Update template to 0.6 API

### PR DESCRIPTION
**Pull request by itowlson**
@benwis Here is the updated Spin template.  This works for me (after munging the git references to local) but please do give it a once over as you know the new API way better than I do!  Thanks!

### CODE REVIEW

**Comment by benwis** [comment]
The question was asked whether we should reexport the leptos-spin-macro crate from leptos-spin, what do you think @itowlson ?

**Comment by benwis** [comment]
Everything else looks good, mostly changes to align with your template vs mine

**Comment by itowlson** [comment]
Sounds like a good idea.  App developers shouldn't need to care that the implementation is split across two crates.

**Comment by benwis** [comment]
> Sounds like a good idea. App developers shouldn't need to care that the implementation is split across two crates.

Do you want to add the export and then update the template to import from leptos-spin?

**Comment by itowlson** [comment]
Hmm, it turns out there's a bit of a nasty.  `leptos_spin` is optional, and used only in the app's `ssr` feature: to make `leptos_spin` mandatory we'd need to put large amounts of `leptos_spin` under feature guard.  Unless there's a clever way to manage that, I'm not sure it's worth it: maybe stick to the current arrangement after all?  What do you reckon?

**Comment by benwis** [comment]
> Hmm, it turns out there's a bit of a nasty. `leptos_spin` is optional, and used only in the app's `ssr` feature: to make `leptos_spin` mandatory we'd need to put large amounts of `leptos_spin` under feature guard. Unless there's a clever way to manage that, I'm not sure it's worth it: maybe stick to the current arrangement after all? What do you reckon?

Ah, then we'll stick with the current thing. I have a PR open to export the leptos-spin version of server form leptos when the spin feature is enabled, so we can just rely on that

**Pull request merged**
